sudo: required
language: python

addons:
    apt:
        packages:
        - build-essential
        - gfortran
        - libatlas-base-dev
        - libopenblas-dev
        - python-dev
        - g++

env:
    - TOXENV=py27
    - TOXENV=docs

install:
    - pip install tox

script:
    - tox